//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzimuthSuite {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalisedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalisedStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzimuthSuite.LocalisedStrings", typeof(LocalisedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close application?.
        /// </summary>
        internal static string MainForm_ApplicationClosePrompt {
            get {
                return ResourceManager.GetString("MainForm_ApplicationClosePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tracks are saved, clear all tracks data?.
        /// </summary>
        internal static string MainForm_ClearTracksPrompt {
            get {
                return ResourceManager.GetString("MainForm_ClearTracksPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device information.
        /// </summary>
        internal static string MainForm_DeviceInformation {
            get {
                return ResourceManager.GetString("MainForm_DeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entries was/were deleted..
        /// </summary>
        internal static string MainForm_EntriesWereDeleted {
            get {
                return ResourceManager.GetString("MainForm_EntriesWereDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string MainForm_Error {
            get {
                return ResourceManager.GetString("MainForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File(s) was/were deleted.
        /// </summary>
        internal static string MainForm_FilesWereDeleted {
            get {
                return ResourceManager.GetString("MainForm_FilesWereDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotkeys tip.
        /// </summary>
        internal static string MainForm_HotKeysTip {
            get {
                return ResourceManager.GetString("MainForm_HotKeysTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl + P  Save screenshot|Ctrl + S  Save tracks|Ctrl + L  Link ON / OFF|Ctrl + H  View current log|Ctrl + 🠗  Collapse remotes|Ctrl + 🠕  Expand remotes|Ctrl + R  Resonder settings editor|Ctrl + I  Show this tooltip.
        /// </summary>
        internal static string MainForm_HotkeysToolTipText {
            get {
                return ResourceManager.GetString("MainForm_HotkeysToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        internal static string MainForm_Information {
            get {
                return ResourceManager.GetString("MainForm_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing outPort on.
        /// </summary>
        internal static string MainForm_InitializingOutPortOn {
            get {
                return ResourceManager.GetString("MainForm_InitializingOutPortOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a name of acrhive....
        /// </summary>
        internal static string MainForm_LogArchiveDialogTitle {
            get {
                return ResourceManager.GetString("MainForm_LogArchiveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log directory compressed to.
        /// </summary>
        internal static string MainForm_LogArchiveResult {
            get {
                return ResourceManager.GetString("MainForm_LogArchiveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all log entries? (This action cannot be undone!).
        /// </summary>
        internal static string MainForm_LogDeleteAllEntriesPrompt {
            get {
                return ResourceManager.GetString("MainForm_LogDeleteAllEntriesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all log files less than 2 kB? (This action cannot be undone!).
        /// </summary>
        internal static string MainForm_LogDeleteEmptyEntriesPrompt {
            get {
                return ResourceManager.GetString("MainForm_LogDeleteEmptyEntriesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log file.
        /// </summary>
        internal static string MainForm_LogFile {
            get {
                return ResourceManager.GetString("MainForm_LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There were some problems during archive creation, log entries will not be deleted.
        /// </summary>
        internal static string MainForm_LogMoveToArchiveProblemsResult {
            get {
                return ResourceManager.GetString("MainForm_LogMoveToArchiveProblemsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log directory compressed to.
        /// </summary>
        internal static string MainForm_LogMoveToArchiveResult {
            get {
                return ResourceManager.GetString("MainForm_LogMoveToArchiveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log playback is currently active, do you want to abort it?.
        /// </summary>
        internal static string MainForm_LogPlaybackAbortPrompt {
            get {
                return ResourceManager.GetString("MainForm_LogPlaybackAbortPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a log file to playback....
        /// </summary>
        internal static string MainForm_LogPlaybackSelectDialogTitle {
            get {
                return ResourceManager.GetString("MainForm_LogPlaybackSelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop playback.
        /// </summary>
        internal static string MainForm_LogPlaybackStopBtnText {
            get {
                return ResourceManager.GetString("MainForm_LogPlaybackStopBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move all log entries to an archive? (This action cannot be undone!).
        /// </summary>
        internal static string MainForm_MoveLogsToArchivePrompt {
            get {
                return ResourceManager.GetString("MainForm_MoveLogsToArchivePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playback....
        /// </summary>
        internal static string MainForm_Playback {
            get {
                return ResourceManager.GetString("MainForm_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на playback is finished.
        /// </summary>
        internal static string MainForm_PlaybackIsFinished {
            get {
                return ResourceManager.GetString("MainForm_PlaybackIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question.
        /// </summary>
        internal static string MainForm_Question {
            get {
                return ResourceManager.GetString("MainForm_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remote Address.
        /// </summary>
        internal static string MainForm_RemoteAddress {
            get {
                return ResourceManager.GetString("MainForm_RemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request was not sent, try to repeat later..
        /// </summary>
        internal static string MainForm_ResponderRequestFailed {
            get {
                return ResourceManager.GetString("MainForm_ResponderRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Responder settings.
        /// </summary>
        internal static string MainForm_ResponderSettingsDialogTitle {
            get {
                return ResourceManager.GetString("MainForm_ResponderSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings has been updated. Restart application to apply new settings?.
        /// </summary>
        internal static string MainForm_RestartPrompt {
            get {
                return ResourceManager.GetString("MainForm_RestartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Screenshot saved.
        /// </summary>
        internal static string MainForm_ScreenshotSaved {
            get {
                return ResourceManager.GetString("MainForm_ScreenshotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string MainForm_Settings {
            get {
                return ResourceManager.GetString("MainForm_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export tracks to....
        /// </summary>
        internal static string MainForm_TracksExportDialogTitle {
            get {
                return ResourceManager.GetString("MainForm_TracksExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tracks are not saved. Do you want to save it before exit?.
        /// </summary>
        internal static string MainForm_TracksSavePrompt {
            get {
                return ResourceManager.GetString("MainForm_TracksSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning!.
        /// </summary>
        internal static string MainForm_Warning {
            get {
                return ResourceManager.GetString("MainForm_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Water salinity.
        /// </summary>
        internal static string SettingsEditor_WaterSalinityDialogTitle {
            get {
                return ResourceManager.GetString("SettingsEditor_WaterSalinityDialogTitle", resourceCulture);
            }
        }
    }
}
